name: Manual workflow
on:
  schedule:
    - cron: '22 10 * * 3'
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo'
        # Default value if no value is explicitly provided
        default: 'argakiig/raiblocks'
        # Input has to be provided for the workflow to run
        required: true
      branch:
        description: 'branch'
        default: 'develop'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout 
      run: echo "Hello ${{ github.event.inputs.repo }}:${{ github.event.inputs.branch }}"
